### PR TITLE
copies by reference instead of reconstructing the whole tuple

### PR DESCRIPTION
**Pull request by issy123**

### CODE REVIEW

**Comment by issy123** [comment]
since we only use the tuple in two places, where one of the two places uses the copy i've made the copy use reference instead of reconstructing the whole tuple since that's not necessary.
The deletion has also changed to de-reference instead of setting the array's length to 0


image

**Comment by isaac-mason** [comment]
@issy123 I see you've got an open PR in the original repo: https://github.com/schteppe/p2.js/pull/366

Are there other improvements in that PR that you think should be brought over?

**Comment by issy123** [comment]
No not really tbh

most of my changes were bullshit

**Comment by isaac-mason** [comment]
Haha, no worries then :)

**Pull request merged**
